### ISSUE TITLE
i love you and love this repo

### ISSUE THREAD

**Issue by folz** [jxnl/pycon2016-datatalks#2]
thought you'd like to know

**Comment by jxnl** [comment]
@AlJohri ? 

I think it'll be ok since these are public videos hosted without advertisments.

**Comment by folz** [comment]
no this is unacceptable i insist u pay for damages out of ur own pocket right now

i can collect on behalf of youtube make the check out to @folz and i'll handle the rest

**Comment by jxnl** [comment]
ok
